# Generated by Django 3.2.13 on 2022-05-15 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=40)),
                ('factory_reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('factory_long_coordinates', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('factory_lat_coordinates', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('factory_creating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_creating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_factory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.factory')),
            ],
        ),
    ]
